version: '3.8'
services:
  api:
    image: chat-gpt-assistance-api:latest
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    networks:
      - chat-gpt-assistance-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  web:
    image: chat-gpt-assistance-ui:latest
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - chat-gpt-assistance-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
networks:
  chat-gpt-assistance-network:
